# Generated by Django 4.1 on 2022-08-18 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pon el nombre del genero', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogoPeliculas.director'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Pon el nombre de la película', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now, help_text='Pon aquí de que va la película', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genre',
            field=models.ManyToManyField(to='catalogoPeliculas.genero'),
        ),
    ]
